version: 2.1

jobs:
  install:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:10.15.3 # the primary container, where your job's commands are run

    working_directory: ~/main

    steps:
      - checkout # check out the code in the project directory

      - attach_workspace:
          at: ~/main
  
      - run:
          name: install
          command: npm ci

      - save_cache:
          key: init
          paths:
            - node_modules

      - persist_to_workspace:
          root: ./
          paths:
            - ./
            - ./node_modules/
  
  test:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:10.15.3 # the primary container, where your job's commands are run
    
    working_directory: ~/main

    steps:
      - checkout # check out the code in the project directory

      - attach_workspace:
          at: ~/main

      - run:
          name: test
          command: npm test

      - persist_to_workspace:
          root: ./
          paths:
            - ./
            - ./node_modules/

workflows:
  install_and_test:
    jobs:
      - install
      - test:
          requires:
            - install